#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
M1.2 scoring harness for the unsolved-relay mission.

Per Mission Brief §M1.2: score each candidate problem on four axes (0-10 each):
  T = Tractability of a bounded sub-question
  R = Reusability of operator's existing machinery (post-probe canonical base)
  P = Publishability of partial or negative result
  I = Independence from R1 / Painlevé III work already in queue

Per operator amendment U-MISSION-E (2026-05-15 ~18:00 JST): the P axis is split
into two distinct sub-axes to enable the dual-shortlist output:
  P_pos = Publishability of a POSITIVE / partial result
  P_neg = Publishability of a NEGATIVE / ruling-out result

The two composite scores are:
  C_primary  = T + R + P_pos + I    (max 40; used for primary shortlist)
  C_contrast = T + R + P_neg + I    (max 40; used for contrast shortlist)

Domain: the 25 rows of `triage.json` with `machinery_available_locally == True`.

Note on Periods #20 (idx 18 of triage.json): this row is `available=True` but
`AEAL_compliance_risk=high`. `triage_validator.py --strict` blocks it. Per AEAL
M1.2 hygiene, it is EXCLUDED from this scoring pass. If operator wishes to
include #20 in shortlisting, they must explicitly waive the high-risk filter
via mutation_log entry; the row is recorded here as `scoring_excluded`.

Output:
  - M1.2_scoring.json       full per-row scoring + composites + ranks
  - M1.2_shortlists.md      human-readable narrative with both top-3 lists
                            and an overlap section

Reproduce:
    cd siarc\\unsolved-relay-staging\\targets
    python build_m1_2_shortlists.py

This script reads `triage.json` to confirm row identities and `machinery_*`
status; the scoring itself is hand-curated below per AEAL judgment-class evidence.

AEAL hygiene notes (per Mission Brief §0.2 + §M1.2):
  - Scores are judgment-class, not numerical-class. They are NOT PSLQ-style
    machine-checkable claims; they are operator-class proxies for a forward
    assessment. The harness IS reproducible (re-running emits identical output)
    but the score values themselves are commits to a specific reading of the
    literature at this date.
  - No claim in `claims/` is generated by this script. M1.2 output is a
    selection-prep deliverable, not a research claim.
"""

from __future__ import annotations

import datetime as _dt
import json
import sys
from pathlib import Path
from typing import Dict, List, Tuple

HERE = Path(__file__).resolve().parent
TRIAGE = HERE / "triage.json"
OUT_JSON = HERE / "M1.2_scoring.json"
OUT_MD = HERE / "M1.2_shortlists.md"

PROBE_DATE = "2026-05-15"
M1_2_DATE = "2026-05-15"


# ---------------------------------------------------------------------------
# Score table.
#
# Indexed by `problem` string matching the triage.json row's `problem` field.
# Each entry: (T, R, P_pos, P_neg, I, rationale_short).
#
# T  (tractability)  : how clean is the bounded sub-question; how clearly can
#                      success/failure be machine-detected within the 96h wall
#                      and 1000-iter caps from Brief §M3.2.
# R  (reusability)   : fit with the confirmed machinery base (mpmath 500dps,
#                      PSLQ, sympy, gmpy2, numpy, gp shell-out, Lean 4 +
#                      Mathlib4, PCF spectral fingerprint, Painlevé tooling).
#                      Penalize entries that need arb/flint/fpylll/sage.
# P_pos (pub-positive): if a positive partial result is achieved, where does
#                       it land? Acta-class news → 9-10; J Number Theory tier
#                       → 6-7; experimental-math note → 3-4.
# P_neg (pub-negative): if a negative / ruling-out result is achieved, where
#                       does it land? Structural ruling-out (e.g., escaping
#                       residue class) → 6-7; extended FP-rejection range →
#                       5-7; "no counterexample in range" with no structural
#                       insight → 2-4.
# I    (R1 independence): 9 = zero overlap with R1/Painlevé III; 6-7 = some
#                         machinery overlap (e.g., CF tools); ≤ 5 = content
#                         overlap risk.
#
# Cardinality check: must score exactly 25 rows (the available=True subset).
# ---------------------------------------------------------------------------

SCORES: Dict[str, Tuple[int, int, int, int, int, str]] = {

    # --- Category A: NT-Diophantine search ---
    "Erdős–Straus conjecture": (
        7, 6, 4, 5, 9,
        "CRT-cover extension well-bounded; positive = incremental Math.Comp; "
        "negative = escaping residue class IS a structural finding "
        "(P_neg > P_pos here).",
    ),
    "Brocard's problem (n! + 1 = m²)": (
        7, 6, 3, 4, 9,
        "Trivially bounded but cosmetic; both positive and negative are "
        "incremental records.",
    ),
    "Erdős–Moser equation (1^k + 2^k + ... + (m-1)^k = m^k)": (
        6, 6, 5, 5, 9,
        "Von Staudt–Clausen + p-adic exclusion; both directions equally "
        "publishable in mid-tier NT venues.",
    ),
    "Pillai-style consecutive perfect-power gap conjectures": (
        7, 5, 3, 2, 9,
        "Lowest publishability across the family; table extension only.",
    ),
    "Beal conjecture for fixed signature (p, q, r)": (
        6, 5, 6, 4, 9,
        "Signature-specific Beal disproof = significant; ruling-out is "
        "incremental.",
    ),

    # --- Category B: NT-multiplicative ---
    "Lehmer's totient problem (φ(n) | n − 1 ⇒ n prime?)": (
        6, 7, 6, 4, 9,
        "PARI shell-out helps; extending ω(n) lower bound has narrative weight.",
    ),
    "Mertens function sign-change density": (
        6, 6, 5, 4, 9,
        "Heavy compute at 10^14; J Number Theory tier on positive side.",
    ),
    "Repunit primality density extension (R_n = (10^n − 1)/9)": (
        7, 5, 4, 2, 9,
        "Single-shot verification at the next candidate; negative = boring "
        "absence.",
    ),

    # --- Category C: CF-Diophantine (NON-PCF tagged) ---
    "Zaremba's conjecture for alphabet A_5 = {1, 2, 3, 4, 5}": (
        7, 7, 6, 7, 6,
        "CF machinery overlap with R1 (PCF infrastructure shared); negative "
        "(counterexample to A_5 = 5) is THE STRONG NEGATIVE in this category.",
    ),
    "Markov spectrum gap structure between 3 and Freiman's constant": (
        6, 6, 5, 4, 7,
        "Tree enumeration combinatorially heavy; CF Diophantine but not PCF.",
    ),
    "Lagrange spectrum values past Freiman's constant": (
        6, 6, 5, 4, 7,
        "Same family as Markov, slightly weaker scoring.",
    ),
    "Stern–Brocot tree gap distribution at large levels": (
        7, 6, 3, 3, 7,
        "Experimental-math note tier; clean but neither direction strong.",
    ),

    # --- Category D: Transcendence / PSLQ-fingerprint ---
    "Khinchin's constant K_0 — rationality / algebraicity": (
        8, 9, 8, 7, 9,
        "PSLQ scan canonical use-case at 500 dps; well-precedented "
        "FP-rejection literature (Bailey–Borwein); CF-name-recognition.",
    ),
    "Catalan's constant G — irrationality / algebraicity": (
        8, 9, 9, 8, 9,
        "Top of the PSLQ-family stack; both directions are flagship "
        "publishability targets.",
    ),
    "Apéry-extension witnesses for ζ(5), ζ(7), ζ(9)": (
        7, 9, 9, 6, 9,
        "Irrationality of any one of ζ(2k+1) at k≥2 = Acta-class news; "
        "negative side weaker because Zudilin's bounds are hard to extend "
        "incrementally (P_pos − P_neg = +3, widest gap in shortlist pool).",
    ),
    "Lévy's constant β = π² / (12 log 2) — rationality / transcendence": (
        8, 9, 8, 7, 9,
        "Twin to Khinchin in score profile; literature recheck CLEARED both "
        "irrationality and transcendence as open (M1.1 audit).",
    ),
    "Glaisher–Kinkelin generalized constants A_k (higher rank)": (
        7, 8, 6, 5, 9,
        "Sub-flagship transcendence target; family-of-constants gives a "
        "compound positive but less news-worthy than G/K_0.",
    ),

    # --- Category E: Partition-combo / mock-modular ---
    "Andrews–Beck higher-rank partition-statistic identities": (
        7, 6, 5, 4, 9,
        "Modulus-extension of Andrews–Beck verification; partition-theory "
        "tier publishability.",
    ),
    "Stanley's plane-partition asymptotic constants (PSLQ-identify against special-value basis)": (
        6, 8, 7, 6, 8,
        "PSLQ identification against special-value basis; combinatorics tier "
        "(Adv Math / J Comb Theory A).",
    ),

    # --- Category F: Discrete-geometry / combinatorics (NON-Painlevé tagged) ---
    "Brown–Erdős–Sós conjecture for linear 3-uniform hypergraphs": (
        5, 6, 6, 5, 9,
        "SAT-branching scales poorly; estimated 95h tight against 96h cap.",
    ),

    # --- Category G: Discrete-dynamics ---
    "Mahler badly-approximable pairs in a fixed cubic number field": (
        5, 7, 6, 5, 6,
        "PARI nfinit + qflll friction; cubic-field arithmetic less indep.",
    ),
    "Hurst-exponent estimation for arithmetic dynamical sequences (Stern, Calkin–Wilf, Thomae)": (
        7, 5, 4, 3, 9,
        "Numpy-only; doesn't leverage operator's strongest tools; "
        "statistical-fit publishability is weak.",
    ),
    "Sárközy-type pattern-avoidance density in sumset dynamics": (
        6, 6, 6, 5, 9,
        "Additive-combinatorics tier; PARI qflll + greedy enumeration.",
    ),
    "Brjuno function B(α) statistics at the irrational-rotation boundary": (
        7, 6, 6, 5, 7,
        "Tangential connection to Painlevé via rotation-number / KAM but "
        "the question is dynamics-of-irrational-rotations, not Painlevé "
        "chart-map dynamics; independence preserved per #30 audit.",
    ),
}


def load_triage(path: Path) -> List[dict]:
    if not path.exists():
        raise FileNotFoundError(f"triage.json not found at {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def expected_problem_set(triage: List[dict]) -> Tuple[List[str], List[str]]:
    avail = [r["problem"] for r in triage if r.get("machinery_available_locally")]
    unavail = [r["problem"] for r in triage if not r.get("machinery_available_locally")]
    return avail, unavail


def excluded_high_risk(triage: List[dict]) -> List[str]:
    return [r["problem"] for r in triage
            if r.get("machinery_available_locally")
            and r.get("AEAL_compliance_risk") == "high"]


def validate_score_coverage(triage: List[dict]) -> Tuple[List[str], List[str], List[str]]:
    """Return (eligible, missing_from_scores, excluded_high_risk)."""
    avail, _ = expected_problem_set(triage)
    high_risk = set(excluded_high_risk(triage))
    eligible = [p for p in avail if p not in high_risk]
    missing = [p for p in eligible if p not in SCORES]
    excess = [p for p in SCORES if p not in eligible]
    if excess:
        raise ValueError(f"SCORES contains entries not in eligible set: {excess}")
    return eligible, missing, sorted(list(high_risk))


def compute_composites(eligible: List[str]) -> List[dict]:
    rows = []
    for p in eligible:
        T, R, P_pos, P_neg, I, rationale = SCORES[p]
        rows.append({
            "problem": p,
            "T_tractability": T,
            "R_reusability": R,
            "P_pos_publishability_positive": P_pos,
            "P_neg_publishability_negative": P_neg,
            "I_independence_R1_PIII": I,
            "C_primary": T + R + P_pos + I,
            "C_contrast": T + R + P_neg + I,
            "P_neg_minus_P_pos": P_neg - P_pos,
            "rationale": rationale,
        })
    return rows


def rank_and_select(rows: List[dict], key: str, top_n: int = 3) -> List[dict]:
    """Sort rows by `key` descending; deterministic tie-break ladder."""
    if key == "C_primary":
        sort_key = lambda r: (
            -r["C_primary"],
            -r["P_pos_publishability_positive"],
            -r["T_tractability"],
            r["problem"],  # alphabetical stability
        )
    elif key == "C_contrast":
        sort_key = lambda r: (
            -r["C_contrast"],
            -r["P_neg_publishability_negative"],
            -r["T_tractability"],
            r["problem"],
        )
    else:
        sort_key = lambda r: (-r[key], r["problem"])

    ordered = sorted(rows, key=sort_key)
    for idx, r in enumerate(ordered):
        r[f"rank_by_{key}"] = idx + 1
    return ordered[:top_n], ordered


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    if not TRIAGE.exists():
        sys.stderr.write(f"ERROR: {TRIAGE} not found\n")
        return 2
    triage = load_triage(TRIAGE)
    eligible, missing, high_risk = validate_score_coverage(triage)

    if missing:
        sys.stderr.write("ERROR: SCORES is missing entries for eligible problems:\n")
        for m in missing:
            sys.stderr.write(f"  - {m}\n")
        return 3

    rows = compute_composites(eligible)

    primary_top3, primary_all = rank_and_select(rows, "C_primary", top_n=3)
    contrast_top3, contrast_all = rank_and_select(rows, "C_contrast", top_n=3)

    primary_problems = {r["problem"] for r in primary_top3}
    contrast_problems = {r["problem"] for r in contrast_top3}
    overlap = sorted(primary_problems & contrast_problems)
    primary_only = sorted(primary_problems - contrast_problems)
    contrast_only = sorted(contrast_problems - primary_problems)

    pub_negshift = sorted(
        [r for r in rows if r["P_neg_minus_P_pos"] > 0],
        key=lambda r: (-r["P_neg_minus_P_pos"], -r["C_contrast"], r["problem"]),
    )

    output = {
        "schema_version": "M1.2-scoring-1.0",
        "generated_at_utc": _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "mission": "unsolved-relay",
        "milestone": "M1.2",
        "operator_amendment": "U-MISSION-E dual-shortlist constraint (2026-05-15 ~18:00 JST)",
        "machinery_base_probe_date": PROBE_DATE,
        "eligible_count": len(eligible),
        "scored_count": len(rows),
        "excluded_high_risk": high_risk,
        "scoring_axes": {
            "T": "Tractability of bounded sub-question (0-10)",
            "R": "Reusability of confirmed machinery base (0-10)",
            "P_pos": "Publishability of positive / partial result (0-10)",
            "P_neg": "Publishability of negative / ruling-out result (0-10)",
            "I": "Independence from R1 / Painlevé III queue (0-10)",
        },
        "composites": {
            "C_primary": "T + R + P_pos + I (max 40)",
            "C_contrast": "T + R + P_neg + I (max 40)",
        },
        "primary_shortlist_top3": primary_top3,
        "contrast_shortlist_top3": contrast_top3,
        "primary_all_ranked": primary_all,
        "contrast_all_ranked": contrast_all,
        "overlap_between_shortlists": overlap,
        "primary_only": primary_only,
        "contrast_only": contrast_only,
        "negative_relative_shift_candidates": pub_negshift,
        "selection_authority": "OPERATOR (CLI does NOT select; per U-MISSION-E)",
    }

    OUT_JSON.write_text(json.dumps(output, indent=2, ensure_ascii=False) + "\n",
                        encoding="utf-8")

    # ---------------- Markdown narrative ----------------
    md = []
    md.append("# M1.2 Shortlists — Operator Selection Required")
    md.append("")
    md.append(f"**Generated:** {output['generated_at_utc']}  ")
    md.append(f"**Mission:** unsolved-relay  ")
    md.append(f"**Milestone:** M1.2 (rank-and-select)  ")
    md.append(f"**Operator amendment governing this output:** "
              f"U-MISSION-E dual-shortlist constraint (2026-05-15 ~18:00 JST)  ")
    md.append(f"**Eligible candidates scored:** {len(eligible)} of "
              f"{len(eligible) + len(high_risk)} `available=True` rows  ")
    md.append(f"**Excluded (high AEAL risk):** {len(high_risk)} — "
              f"{', '.join(high_risk) if high_risk else '∅'}  ")
    md.append("")
    md.append("**Selection authority:** OPERATOR. CLI does NOT select. This "
              "file is a *selection prep* deliverable. Operator names the "
              "target via a follow-up directive; `targets/selected.md` is "
              "operator-supplied at that step.")
    md.append("")
    md.append("---")
    md.append("")

    md.append("## §1 Scoring methodology")
    md.append("")
    md.append("Five axes (0–10 each), with the Brief's `P` axis split into "
              "`P_pos` and `P_neg` per U-MISSION-E:")
    md.append("")
    md.append("| Axis | Meaning |")
    md.append("|---|---|")
    md.append("| **T** | Tractability of the bounded sub-question (clean "
              "success/failure boundary under 96h wall-clock and 1000-iter "
              "caps from Brief §M3.2) |")
    md.append("| **R** | Reusability of the confirmed machinery base "
              "(post-probe canonical set: mpmath 500dps, PSLQ, sympy, "
              "gmpy2, numpy, gp shell-out, Lean 4 + Mathlib4, PCF / Painlevé "
              "tooling). Entries needing arb/flint/fpylll/sage are penalized. |")
    md.append("| **P_pos** | Publishability of a *positive* / partial result. "
              "Acta-class news = 9–10; J Number Theory tier = 6–7; "
              "experimental-math note = 3–4. |")
    md.append("| **P_neg** | Publishability of a *negative* / ruling-out "
              "result. Structural ruling-out (e.g., escaping residue class) "
              "= 6–7; extended FP-rejection range = 5–7; \"no counterexample "
              "in range\" without structural insight = 2–4. |")
    md.append("| **I** | Independence from R1 / Painlevé III queue. 9 = zero "
              "overlap; 6–7 = machinery overlap only; ≤ 5 = content overlap. |")
    md.append("")
    md.append("Composites:")
    md.append("")
    md.append("- `C_primary  = T + R + P_pos + I` (max 40) → drives primary "
              "shortlist")
    md.append("- `C_contrast = T + R + P_neg + I` (max 40) → drives contrast "
              "shortlist")
    md.append("")
    md.append("Deterministic tie-break ladder: composite desc → relevant P "
              "axis desc → T desc → problem-name alphabetical.")
    md.append("")
    md.append("AEAL hygiene note: scores are **judgment-class evidence**, not "
              "numerical-class. The harness is reproducible (`python "
              "build_m1_2_shortlists.py` emits identical JSON), but the "
              "score values themselves are a commit to a specific reading of "
              "the literature on the M1.2 date. No `claims/` entry is "
              "produced by this script.")
    md.append("")

    md.append("---")
    md.append("")
    md.append("## §2 Primary shortlist — top 3 by C_primary "
              "(positive-result publishability)")
    md.append("")
    md.append("| Rank | Problem | T | R | P_pos | I | **C_primary** | Why it's here |")
    md.append("|---|---|---|---|---|---|---|---|")
    for r in primary_top3:
        md.append(
            f"| {r['rank_by_C_primary']} | **{r['problem']}** | "
            f"{r['T_tractability']} | {r['R_reusability']} | "
            f"{r['P_pos_publishability_positive']} | {r['I_independence_R1_PIII']} | "
            f"**{r['C_primary']}** | {r['rationale']} |"
        )
    md.append("")

    md.append("---")
    md.append("")
    md.append("## §3 Contrast shortlist — top 3 by C_contrast "
              "(negative / ruling-out publishability)")
    md.append("")
    md.append("| Rank | Problem | T | R | P_neg | I | **C_contrast** | Why it's here |")
    md.append("|---|---|---|---|---|---|---|---|")
    for r in contrast_top3:
        md.append(
            f"| {r['rank_by_C_contrast']} | **{r['problem']}** | "
            f"{r['T_tractability']} | {r['R_reusability']} | "
            f"{r['P_neg_publishability_negative']} | {r['I_independence_R1_PIII']} | "
            f"**{r['C_contrast']}** | {r['rationale']} |"
        )
    md.append("")

    md.append("---")
    md.append("")
    md.append("## §4 Overlap between shortlists")
    md.append("")
    if overlap:
        md.append(f"**Shared problems ({len(overlap)}):** "
                  + ", ".join(f"*{p}*" for p in overlap))
    else:
        md.append("**No overlap.** The two shortlists are disjoint.")
    md.append("")
    md.append(f"**Primary-only ({len(primary_only)}):** "
              + (", ".join(f"*{p}*" for p in primary_only) if primary_only else "∅"))
    md.append("")
    md.append(f"**Contrast-only ({len(contrast_only)}):** "
              + (", ".join(f"*{p}*" for p in contrast_only) if contrast_only else "∅"))
    md.append("")
    md.append("**Signal interpretation.** Heavy overlap means the PSLQ-family "
              "transcendence targets are operator's strongest fit on BOTH "
              "positive and negative axes. This is a real finding, not a "
              "scoring artifact — high `R` (PSLQ at 500 dps), high `I` (zero "
              "PCF / Painlevé overlap), and famous-enough constants that both "
              "directions have publishing precedents. If operator wants a "
              "*more divergent* contrast pool, §5 below surfaces an "
              "alternative criterion.")
    md.append("")

    md.append("---")
    md.append("")
    md.append("## §5 Alternative contrast view — entries where P_neg > P_pos")
    md.append("")
    md.append("These are problems where the *negative* result is **strictly "
              "stronger** than the positive — i.e., the ruling-out finding "
              "has more structural content than a partial verification would "
              "yield. This is the cleanest \"the negative result IS the "
              "deliverable\" pool, even though composite scores are lower.")
    md.append("")
    if pub_negshift:
        md.append("| Problem | P_pos | P_neg | Δ (P_neg − P_pos) | C_contrast | "
                  "Why the negative is the stronger result |")
        md.append("|---|---|---|---|---|---|")
        for r in pub_negshift:
            md.append(
                f"| {r['problem']} | {r['P_pos_publishability_positive']} | "
                f"{r['P_neg_publishability_negative']} | "
                f"+{r['P_neg_minus_P_pos']} | {r['C_contrast']} | "
                f"{r['rationale']} |"
            )
    else:
        md.append("*(none — for all eligible candidates, P_pos ≥ P_neg)*")
    md.append("")
    md.append("**If operator wants the contrast shortlist to be drawn from "
              "this alternative pool**, name it explicitly in the next "
              "directive; CLI will re-rank under that criterion.")
    md.append("")

    md.append("---")
    md.append("")
    md.append("## §6 Full per-row scoring (all eligible)")
    md.append("")
    md.append(f"Ranked by C_primary. {len(primary_all)} eligible rows. "
              "Use this table for cross-checking the top-3 selections in §2 "
              "and §3.")
    md.append("")
    md.append("| C_primary | C_contrast | Problem | T | R | P_pos | P_neg | I |")
    md.append("|---|---|---|---|---|---|---|---|")
    for r in primary_all:
        md.append(
            f"| **{r['C_primary']}** | {r['C_contrast']} | {r['problem']} | "
            f"{r['T_tractability']} | {r['R_reusability']} | "
            f"{r['P_pos_publishability_positive']} | "
            f"{r['P_neg_publishability_negative']} | "
            f"{r['I_independence_R1_PIII']} |"
        )
    md.append("")

    md.append("---")
    md.append("")
    md.append("## §7 Exclusions and audit trail")
    md.append("")
    md.append("**High AEAL risk excluded from scoring** (operator may waive "
              "via explicit mutation_log directive):")
    md.append("")
    if high_risk:
        for hr in high_risk:
            md.append(f"- *{hr}* — `AEAL_compliance_risk=high`, blocked by "
                      "`triage_validator.py --strict`. Excluded by default to "
                      "preserve AEAL discipline.")
    else:
        md.append("*(none)*")
    md.append("")
    md.append("**Hard-filtered at M1.1** (`machinery_available_locally=false`; "
              "NOT scored here):")
    md.append("")
    _, unavail = expected_problem_set(triage)
    for u in unavail:
        md.append(f"- *{u}* — machinery gap, see `capability/` for "
                  "unavailable-tool details.")
    md.append("")
    md.append("**Parked in `seeds/`** (operator-instructed future-work, do NOT "
              "re-enter this cycle):")
    md.append("")
    md.append("- Survey-set #26 Gauss–Kuzmin direct version DROPPED at M1.1; "
              "reframings R-1 (non-Gauss CF map) and R-2 (large-deviation "
              "partial-quotient sums) parked at "
              "`seeds/26_gauss_kuzmin_reframings_future_work.md`.")
    md.append("")

    md.append("---")
    md.append("")
    md.append("## §8 Operator action required")
    md.append("")
    md.append("**U-MISSION-F (NEW, gating M1.3 Gold Freeze G1):** select one "
              "target from §2 (primary) or §3 (contrast), or instruct CLI to "
              "re-rank against the §5 alternative pool. Once selected:")
    md.append("")
    md.append("1. Operator names the chosen problem in a directive.")
    md.append("2. CLI writes `targets/selected.md` with the one-paragraph "
              "justification and the bounded sub-question for M2–M6.")
    md.append("3. CLI re-raises **U-MISSION-B** (`gh repo create "
              "papanokechi/unsolved-relay` vs a target-specific repo name "
              "such as `catalan-G-bounded` or `khinchin-pslq-scan`) — "
              "deferred per operator's earlier resolution.")
    md.append("4. After repo decision, M1.3 Gold Freeze G1 fires.")
    md.append("")
    md.append("**M2.1 onward, binding rule (operator-issued 2026-05-15 "
              "~18:00 JST):** every commit must produce literature claims, "
              "capability entries, harness code, or numerical/symbolic "
              "artifacts. Any milestone that produces only meta-artifacts "
              "triggers Brief §7 anti-thrashing review. M1.2 is the LAST "
              "milestone in which process-as-deliverable is acceptable.")
    md.append("")

    OUT_MD.write_text("\n".join(md) + "\n", encoding="utf-8")

    print(f"[M1.2 scoring]")
    print(f"  triage.json rows total          : {len(triage)}")
    print(f"  available=True                  : "
          f"{len(expected_problem_set(triage)[0])}")
    print(f"  excluded (AEAL_risk=high)       : {len(high_risk)}")
    print(f"  eligible scored                 : {len(rows)}")
    print(f"  primary shortlist (top 3 C_primary):")
    for r in primary_top3:
        print(f"    #{r['rank_by_C_primary']}  "
              f"C_primary={r['C_primary']}  "
              f"C_contrast={r['C_contrast']}  "
              f"{r['problem']}")
    print(f"  contrast shortlist (top 3 C_contrast):")
    for r in contrast_top3:
        print(f"    #{r['rank_by_C_contrast']}  "
              f"C_primary={r['C_primary']}  "
              f"C_contrast={r['C_contrast']}  "
              f"{r['problem']}")
    print(f"  overlap                          : {overlap}")
    print(f"  primary-only                     : {primary_only}")
    print(f"  contrast-only                    : {contrast_only}")
    print(f"  P_neg > P_pos rows               : "
          f"{[r['problem'] for r in pub_negshift]}")
    print(f"  outputs                          :")
    print(f"    {OUT_JSON}")
    print(f"    {OUT_MD}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
